### ISSUE TITLE
Unclear documentation (Readme)

### ISSUE THREAD

**Issue by evbo** [leighmcculloch/docker-unison#7]
What does this mean?:

You can then sync a local folder to /unison in the container with:

`$ unison . socket://<docker>:5000/ -auto -batch`

Can you give an example? I blindly copy and pasted the command and of course I get:
`bash: docker: No such file or directory`

**Comment by leighmcculloch** [comment]
You need to replace the `<docker>` with the IP address of your docker machine. To find out what that is run `docker-machine ls` and it should show you something like:

```
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER   ERRORS
default   *        virtualbox   Running   tcp://192.168.99.187:2376           v1.9.1
```

**Comment by jesseditson** [comment]
A common use case here would be `unison . socket://$(docker-machine ip default):5000/ -auto -batch` - you can change "default" to the name of your machine if you are using a different name, this will always pick up the correct IP.

**Comment by Jehu** [comment]
more questions:
- you do not describe (or link to a) how to install unison
- what if i use the new beta-docker without docker-machine?

**Comment by leighmcculloch** [comment]
@Jehu if you use the new beta-docker for mac then you won't need unison for syncing I imagine. Which is fantastic as this docker image was a work around for using docker on Mac and slow file transfers :)

**Comment by Jehu** [comment]
@leighmcculloch this was my hope also as i installed it. but sadly for real volumes are slower than docker stable (feels like 10% slower, or so...).

btw: without docker-machine it is:
`unison . socket://localhost:5000/ -auto -batch`, because docker needs no VirtualBox anymore.

unison can be installed by homebrew: `brew install unison`

i hope to resolve my perfomance problems now... ;-)

**Comment by leighmcculloch** [comment]
@Jehu Thank you, I'm adding notes on how to install unison on Mac to the README in the next version, so hopefully other people will have a better experience. Thanks for sharing how you got it working.
